name: wmdp_replication
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pytorch>=2.0
  - numpy>=1.25
  - pandas>=2.0
  - transformers>=4.46.0
  - datasets>=2.0.0
  - pyyaml>=6.0
  - tqdm
  - accelerate>=1.6.0
  - pip:
      - vastai==0.2.8